# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 重庆大学开源软件镜像站
brand: Chongqing University Open Source Mirror Site
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirrors.cqu.edu.cn"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel

babel_js_extensions: 'es6'

exclude: ['README.md', 'Gemfile*', '*.sh', 'geninfo/', '*.py', '*.tar.gz', 
          'Dockerfile.*']

# Content Related
new_mirrors:
# vim: ts=2 sts=2 sw=2 expandtab
